---
title: "12_ID-check"
author: "zagor"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_caption: yes
    self_contained: yes
    fig_width: 9
    fig_height: 6
    toc: true
    toc_float:
      toc_collapsed: false
    toc_depth: 5
    number_sections: yes
    theme: flatly
    highlight: tango
  pdf_document:
    toc: yes
    toc_depth: '2'
  word_document:
    toc: yes
    toc_depth: '2'
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r,  echo=TRUE, warning=FALSE, message=FALSE}

rm(list = ls(all = TRUE))
gc()


library(magrittr)
library(data.table)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))


```


# input

```{r}

fp = file.path('..', 'output')

fn1 = 'tomato-ath_orthologues-kept_2025-09-24-strict.xlsx'
dt1 = openxlsx::read.xlsx(file.path(fp, fn1))
setDT(dt1)
dt1[1:2, 1:2]
dt1[, to_geneID := sub("(Solyc\\d+)T(\\d+)", "\\1G\\2", to_geneID)]
dt1[1:2, 1:2]


fn2 = 'tomato-ath_orthologues-kept_2025-09-15.xlsx'
dt2 = openxlsx::read.xlsx(file.path(fp, fn2))
setDT(dt2)
dt2[1:2, 1:2]
dt2[, to_geneID := sub("(Solyc\\d+)T(\\d+)", "\\1G\\2", to_geneID)]
dt2[1:2, 1:2]


```


# output

```{r}

openxlsx::write.xlsx(dt1, file.path(fp, fn1), asTable = TRUE)
openxlsx::write.xlsx(dt2, file.path(fp, fn2), asTable = TRUE)

```



# sessionInfo

```{r}

sessionInfo()

```

